# Introduction to PyTorch (Part 1)

## A.1 What is PyTorch

```bash 
PyTorch (https://pytorch.org/) is an open source Python-based deep learning library. 

According to Papers With Code (https://paperswithcode.com/trends), a platform that tracks and analyzes research papers, 

PyTorch has been the most widely used deep learning library for research since 2019 by a wide margin. 

And, according to the Kaggle Data Science and Machine Learning Survey 2022 (https://www.kaggle.com/c/kaggle-survey-2022), 

the number of respondents using PyTorch is approximately 40%, which grows every year.

```

##  The three core components of PyTorch

#### 1. **Tensor library :** PyTorch implements a tensor (array) library for efficient computing.
#### 2. **Automatic differentiation engine Deep learning library**: PyTorch includes utilities to differentiate computations automatically
#### 3. **Deep learning library**: PyTorch’s deep learning utilities make use of its tensor library and automatic differentiation engine.


<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/1.webp" width="400px">

## Sub Categories of Deeplearning
<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/2.webp" width="300px">
<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/3.webp" width="300px">

##  Installing PyTorch

[https://pytorch.org/](https://pytorch.org/get-started/locally/) 

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/4.webp" width="500px">

## Checking Version of Pytorch

In [2]:
import torch

print(torch.__version__)

2.13.0+cu126


In [3]:
print(torch.cuda.is_available())

True


#### Alternative GPU


<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/5.webp" width="500px">

## A.2 Understanding tensors

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/6.webp" width="400px">

### A.2.1 Scalars, vectors, matrices, and tensors

In [4]:
import torch
import numpy as np

# create a 0D tensor (scalar) from a Python integer
tensor0d = torch.tensor(1)

# create a 1D tensor (vector) from a Python list
tensor1d = torch.tensor([1, 2, 3])

# create a 2D tensor from a nested Python list
tensor2d = torch.tensor([[1, 2], 
                         [3, 4]])

# create a 3D tensor from a nested Python list
tensor3d_1 = torch.tensor([[[1, 2], [3, 4]], 
                           [[5, 6], [7, 8]]])

# create a 3D tensor from NumPy array
ary3d = np.array([[[1, 2], [3, 4]], 
                  [[5, 6], [7, 8]]])
tensor3d_2 = torch.tensor(ary3d)  # Copies NumPy array
tensor3d_3 = torch.from_numpy(ary3d)  # Shares memory with NumPy array

In [5]:
ary3d[0, 0, 0]

np.int64(1)

In [6]:
tensor3d_3

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [7]:
ary3d[0, 0, 0] = 999
print(tensor3d_2) # remains unchanged

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [8]:
print(tensor3d_3) # changes because of memory sharing

tensor([[[999,   2],
         [  3,   4]],

        [[  5,   6],
         [  7,   8]]])


### A.2.2 Tensor data types

In [9]:
tensor1d = torch.tensor([1, 2, 3]) # Default 64 bit integer
print(tensor1d.dtype)

torch.int64


In [10]:
# python floats; PyTorch creates tensors with a 32-bit precision

floatvec = torch.tensor([1.0, 2.0, 3.0]) 

print(floatvec.dtype)

torch.float32


In [10]:
# 64-bit integer tensor into a 32-bit float tensor; consuming less memory and computational resources
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)

torch.float32


### A.2.3 Common PyTorch tensor operations

In [14]:
tensor2d = torch.tensor([[1, 2, 3], 
                         [4, 5, 6]])
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
tensor2d.shape

torch.Size([2, 3])

### .vew(), reshape(), .T

#### **.vew()**: requires the original data to be contiguous and will fail if it isn’t
#### **.reshape()**: will work regardless, copying the data if necessary to ensure the desired shape.
#### **.T** to transpose a tensor: flipping it across its diagonal. Note that this is similar to reshaping a tensor

In [16]:
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
# similar to reshape; its must common
tensor2d.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [18]:
# [2, 3] --> [3, 2]

tensor2d.reshape(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [14]:
# similar to reshape; its must common
tensor2d.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [15]:
tensor2d.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

## Matrics Multiplication

In [16]:
tensor2d.matmul(tensor2d.T)

tensor([[14, 32],
        [32, 77]])

In [17]:
tensor2d @ tensor2d.T

tensor([[14, 32],
        [32, 77]])

## Task:
[Other operations](https://docs.pytorch.org/docs/2.13/tensors.html)

## A.3 Seeing models as computation graphs

##  Automatic Differentiation Engine also known as **autograd**

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/7.webp" width="600px">

In [18]:
import torch.nn.functional as F

y = torch.tensor([1.0])  # true label
x1 = torch.tensor([1.1]) # input feature
w1 = torch.tensor([2.2]) # weight parameter
b = torch.tensor([0.0])  # bias unit

z = x1 * w1 + b          # net input
a = torch.sigmoid(z)     # activation & output

loss = F.binary_cross_entropy(a, y)
print(loss)

tensor(0.0852)


## A.4 Automatic differentiation made easy

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/8.webp" width="600px">

## By default, PyTorch destroys the computation graph after calculating the gradients to free memory. 
## However, since we will reuse this computation graph shortly,we set **retain_graph=True** so that it stays in memory

In [19]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

z = x1 * w1 + b 
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)
print(loss)

tensor(0.0852, grad_fn=<BinaryCrossEntropyBackward0>)


In [20]:
grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [21]:
loss.backward()

print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


## A.5 Implementing multilayer neural networks

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/9.webp" width="500px">

## Code disections
```bash
1. class NeuralNetwork(torch.nn.Module):
### Details
Automatically gains the ability to track weights, biases, move to GPUs, and calculate gradients for training.
```
- - -

```bash
2. def __init__(self, num_inputs, num_outputs):
    super().__init__()

### Details
__init__: This initializes the network and defines its architecture (the "blueprint"). It accepts the size of the incoming data (num_inputs) and the size of the desired prediction (num_outputs).

super().__init__(): This is a crucial line in Python. It triggers the initialization of the parent class (torch.nn.Module). Without this, PyTorch won't register the layers you define below it.
```
- - -

```bash
self.layers = torch.nn.Sequential()

torch.nn.Sequential: A convenient wrapper. Instead of passing data manually from layer to layer, Sequential chains them together so that the output of one automatically becomes the input to the next.

```
- - -
```bash
torch.nn.Linear(num_inputs, 30),
torch.nn.ReLU(),


### Details

1. Linear(num_inputs, 30): This is a fully connected layer. It takes num_inputs features (e.g., 10 features of a house) and applies a linear transformation ($Y = XW^T + b$) to project them into a 30-dimensional space.

2. ReLU(): The Rectified Linear Unit activation function. It replaces all negative numbers coming out of the linear layer with 0. Why? It introduces non-linearity, allowing the network to learn complex, curvy patterns instead of just straight lines.

```
- - -

```bash
torch.nn.Linear(20, num_outputs),


The final stop. It maps the 20 hidden features down to the exact number of outputs you need (e.g., 3 outputs if you are classifying images into cats, dogs, or birds). Notice there is no ReLU here, as we want raw, unconstrained values.
```

- - -

```bash
def forward(self, x):
    logits = self.layers(x)
    return logits


forward(self, x): This defines the actual flow of data. When you pass data x into the network, Python executes this method.

logits: The raw, unnormalized outputs generated by the final linear layer.

return logits: Sends the predictions out so you can calculate the error (loss) and update the network.
```
- - -

In [20]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = torch.nn.Sequential(
                
            # 1st hidden layer
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),

            # 2nd hidden layer
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),

            # output layer
            torch.nn.Linear(20, num_outputs),
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits

In [21]:
model = NeuralNetwork(50, 3)

In [24]:
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


### Calculate the parameters
for each layers
$$\text{Total Parameters} = (\text{in\_features} \times \text{out\_features}) + \text{out\_features}$$

In [22]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Total number of trainable model parameters:", num_params)

Total number of trainable model parameters: 2213


## How is weight assigned
a Uniform Distribution ($\mathcal{U}$) bounded by a specific range:

$$\text{Range} = \left[ -\sqrt{k}, +\sqrt{k} \right]$$

Where:
$$k = \frac{1}{\text{in\_features}}$$

Both the weights and the biases are initialized using this exact same range by default.

In [23]:
print(model.layers[0].weight)

Parameter containing:
tensor([[ 0.0979,  0.0412,  0.1005,  ..., -0.0544, -0.0804,  0.0842],
        [-0.0115,  0.0382, -0.0261,  ...,  0.0573,  0.1094,  0.1364],
        [ 0.0162, -0.0050,  0.0752,  ...,  0.1298,  0.1250, -0.0117],
        ...,
        [-0.0312,  0.1319, -0.0954,  ..., -0.1066, -0.0970, -0.0373],
        [ 0.0563, -0.1373, -0.1226,  ...,  0.0154, -0.0969,  0.0113],
        [-0.0872, -0.0098,  0.0322,  ..., -0.0108,  0.1091, -0.1043]],
       requires_grad=True)


In [24]:
torch.manual_seed(123)

model = NeuralNetwork(50, 3)
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [25]:
print(model.layers[0].weight.shape)

torch.Size([30, 50])


## Forward Pass
#### Forward pass refers to calculating **output tensors** from **input tensors**

## Output Result
```bash
grad_fn=<AddmmBackward0>:  

matrix multiplication and 
addition operation. 
PyTorch will use this information when it 
computes gradients during 
backpropagation
```
- - -
```bash

Operation performed, it is an 
Addmm operation. 

Addmm stands for matrix

multiplication (mm) followed by 
an addition (Add).
```
last-used function to compute a variable in the computational graph.
- - -



In [26]:
torch.manual_seed(123)

X = torch.rand((1, 50))
out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)


### Ouput Train model prediction
```bash
torch.no_grad()
```
### computational graph for backpropagation can be wasteful as it performs unnecessary computations and consumes additional memory


In [27]:
with torch.no_grad():
    out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]])


In [28]:
with torch.no_grad():
    out = torch.softmax(model(X), dim=1)
print(out)

tensor([[0.3113, 0.3934, 0.2952]])


## A.6 Setting up efficient data loaders

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/10.webp" width="600px">

In [4]:
import torch
X_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])

y_train = torch.tensor([0, 0, 0, 1, 1])

In [5]:
X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6],
])

y_test = torch.tensor([0, 1])

In [ ]:
from torch.utils.data import Dataset


class ToyDataset(Dataset):
    def __init__(self, X, y):
        self.features = X
        self.labels = y

    def __getitem__(self, index):
        one_x = self.features[index] # set as the list 
        one_y = self.labels[index]        
        return one_x, one_y

    def __len__(self):
        return self.labels.shape[0]

train_ds = ToyDataset(X_train, y_train)
test_ds = ToyDataset(X_test, y_test)

In [12]:
len(train_ds[0])

2

In [13]:
from torch.utils.data import DataLoader
# DataLoader: parallelizing data loading and preprocessing
# num_workers: 0 the data loading will be done in the main process and not in separate worker processes.
torch.manual_seed(123)

train_loader = DataLoader(
    dataset=train_ds, # 
    batch_size=2,
    shuffle=True,
    num_workers=0
)

In [14]:
test_ds = ToyDataset(X_test, y_test)

test_loader = DataLoader(
    dataset=test_ds,
    batch_size=2,
    shuffle=False,
    num_workers=0
)

In [15]:
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx+1}:", x, y)

Batch 1: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])
Batch 2: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Batch 3: tensor([[ 2.7000, -1.5000]]) tensor([1])


In [16]:
train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0,
    drop_last=True
)

In [17]:
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx+1}:", x, y)

Batch 1: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Batch 2: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])


<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/11.webp" width="600px">

## A.7 A typical training loop

In [23]:
import torch.nn.functional as F


torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

num_epochs = 3

for epoch in range(num_epochs):
    
    model.train()
    for batch_idx, (features, labels) in enumerate(train_loader):

        logits = model(features)
        
        loss = F.cross_entropy(logits, labels) # Loss function
        
        optimizer.zero_grad() # Sets the gradients from the previou round to 0 to prevent unintend gradient accumulation
        loss.backward()  # Compute the gradient of the loss given the model parameters
        optimizer.step() # The optimizer uses the gradients to update the model parameters
    
        ### LOGGING
        print(f"Epoch: {epoch+1:03d}/{num_epochs:03d}"
              f" | Batch {batch_idx+1:03d}/{len(train_loader):03d}"
              f" | Train/Val Loss: {loss:.2f}")

    model.eval()
    # Optional model evaluation

Epoch: 001/003 | Batch 001/002 | Train/Val Loss: 0.75
Epoch: 001/003 | Batch 002/002 | Train/Val Loss: 0.65
Epoch: 002/003 | Batch 001/002 | Train/Val Loss: 0.44
Epoch: 002/003 | Batch 002/002 | Train/Val Loss: 0.13
Epoch: 003/003 | Batch 001/002 | Train/Val Loss: 0.03
Epoch: 003/003 | Batch 002/002 | Train/Val Loss: 0.00


In [24]:
model.eval()

with torch.no_grad():
    outputs = model(X_train)

print(outputs)

tensor([[ 2.8569, -4.1618],
        [ 2.5382, -3.7548],
        [ 2.0944, -3.1820],
        [-1.4814,  1.4816],
        [-1.7176,  1.7342]])


In [29]:
import torch

# Create a tensor with mixed large and small numbers
x = torch.tensor([0.001, 1000.0, 55000.3])

# 1. Default Behavior (Scientific notation triggered)
print(x)
# Output: tensor([1.0000e-03, 1.0000e+03, 5.5000e+04])

# 2. Apply your configuration
torch.set_printoptions(sci_mode=False)

# 3. New Behavior (Standard decimal notation)
print(x)
# Output: tensor([    0.0010,  1000.0000, 55000.3008])


tensor([1.0000e-03, 1.0000e+03, 5.5000e+04])
tensor([    0.0010,  1000.0000, 55000.3008])


In [26]:
torch.set_printoptions(sci_mode=False)
probas = torch.softmax(outputs, dim=1)
print(probas)

predictions = torch.argmax(probas, dim=1)
print(predictions)

tensor([[0.9991, 0.0009],
        [0.9982, 0.0018],
        [0.9949, 0.0051],
        [0.0491, 0.9509],
        [0.0307, 0.9693]])
tensor([0, 0, 0, 1, 1])


In [41]:
predictions = torch.argmax(outputs, dim=1)
print(predictions)

tensor([0, 0, 0, 1, 1])


In [30]:
predictions == y_train

tensor([True, True, True, True, True])

In [31]:
torch.sum(predictions == y_train)

tensor(5)

In [32]:
def compute_accuracy(model, dataloader):

    model.eval()
    correct = 0.0
    total_examples = 0
    
    for idx, (features, labels) in enumerate(dataloader):
        
        with torch.no_grad():
            logits = model(features)
        
        predictions = torch.argmax(logits, dim=1)
        compare = labels == predictions
        correct += torch.sum(compare)
        total_examples += len(compare)

    return (correct / total_examples).item()

In [33]:
compute_accuracy(model, train_loader)

1.0

In [34]:
compute_accuracy(model, test_loader)

1.0

## A.8 Saving and loading models

In [47]:
torch.save(model.state_dict(), "model.pth")

In [48]:
model = NeuralNetwork(2, 2) # needs to match the original model exactly
model.load_state_dict(torch.load("model.pth", weights_only=True))

<All keys matched successfully>